name: BizAthlete
favicon: null
layout_spectrum: 0.6631386142689735
typography_spectrum: 0.3463057819753885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeaec'
    - '#62c8f3'
    - '#bed62f'
    - '#7569ac'
    - '#491f5a'
  brandStrength: 0.9393128431402147
  lightness: 0.6839498272165656
  saturation: 0.7813945307862014
  rhythmicContrast: 0.6017064480111003
purpose: []
